// <auto-generated />
using ECommerceWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241125004008_AdminSeeding")]
    partial class AdminSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ECommerceWebAPI.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "hashed_password",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ECommerceWebAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Test Product",
                            ImageUrl = "Images/p2.jpg",
                            Name = "Sample Product",
                            Price = 100m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            ImageUrl = "Images/p2.jpg",
                            Name = "Product 2",
                            Price = 20.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description 3",
                            ImageUrl = "Images/p3.jpg",
                            Name = "Product 3",
                            Price = 30.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
